fix: sitemap deep_scrape_curation_status enum type name
Changed from 'SitemapCurationStatusEnum' (PascalCase, doesn't exist)
to 'sitemap_import_curation_status' (snake_case, matches DB).

This was incorrectly set in commit 1b5a044 and caused:
UndefinedObjectError: type 'SitemapCurationStatusEnum' does not exist

Fixes sitemap processing pipeline crash.